env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  TERM: xterm-256color

window:
  # Window dimensions in character columns and lines
  dimensions:
    columns: 160
    lines: 80

  # Adds this many blank pixels of padding around the window
  padding:
    x: 4
    y: 4

  # Window decorations
  decorations: full

  startup_mode: Maximized

  dynamic_title: true

  option_as_alt: Both

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: JetBrainsMono Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: JetBrainsMono Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: JetBrainsMono Nerd Font
    # Style can be specified to pick a specific face.
    # style: Regular

  # Point size of the font
  size: 20

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  glyph_offset:
    x: 0
    y: 0

# Should display the render timer
debug.render_timer: false

colors:
  # Default colors
  primary:
    background: '0x1E1D2F'
    foreground: '0xD9E0EE'

  cursor:
    text: '0x1E1D2F'
    cursor: '0xF5E0DC'

  # Normal colors
  normal:
    black: '0x6E6C7E'
    red: '0xF28FAD'
    green: '0xABE9B3'
    yellow: '0xFAE3B0'
    blue: '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan: '0x89DCEB'
    white: '0xD9E0EE'

  # Bright colors
  bright:
    black: '0x988BA2'
    red: '0xF28FAD'
    green: '0xABE9B3'
    yellow: '0xFAE3B0'
    blue: '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan: '0x89DCEB'
    white: '0xD9E0EE'

  indexed_colors:
    - { index: 16, color: '0xF8BD96' }
    - { index: 17, color: '0xF5E0DC' }

# Visual Bell
bell:
  animation: EaseOutExpo
  duration: 0

# Background opacity
window.opacity: 1.0

# Mouse bindings
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  # Click settings 
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true

  url:
    launcher: open
  
  faux_scrolling_lines: 1

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

# Style of the cursor
cursor.style: Block

# Live config reload (changes require restart)
live_config_reload: true
theme: Catppuccin

# Shell
shell:
  program: /bin/zsh
