#!/usr/bin/zsh

if ! [[ -f setup ]]; then
  echo "run this from the root of the dotfiles project"
  exit 1;
fi

# I could do some more advanced globbing stuff
# but kind don't want to break stuff
clear() {
  for file in .zshrc .config/zsh .config/i3 .config/nvim .config/rofi .config/tmux .config/user-dirs.dirs .gitconfig .Xresources .gdbinit .local/share/fonts .local/share/rofi .local/share/nvim; do
    # something bad happened, gtfo
    [[ -z $HOME || -z $file ]] && exit 1;
	  rm -rf $HOME/$file;
  done; 
}

# clear out all the existing config files stow would link to 
## NOTE: if somehow $file (and $HOME (even worse)) is empty
## this would be like really bad (delete / or ~) but im lazy so
## use caution if you want to do this
if [[ $1 == "clear" ]]; then
  clear;
  exit 0;
fi

echo "Y" | sudo pacman -Syyu yay
for app in alacritty tmux neovim nitrogen nordic-wallpaper z ripgrep stow i3blocks yad suckless-tools python python-pip python-neovim zsh ruby npm bun fzf tailscale; do
	echo "Y" | sudo pacman -S $app;
	if [[ $? -eq 1 ]]; then
		yay $app;
	fi
done

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
git clone https://github.com/NvChad/starter ~/.config/nvim --depth 1 && nvim
sudo chsh -s /bin/zsh
sudo mkdir -p ~/.data/z ~/.data/zsh
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
mv ~/.oh-my-zsh/* ~/.config/zsh/omz/ && rm -rf ~/.oh-my-zsh

# go into tmux and <PREFIX> + I
