#!/usr/bin/zsh

for app in alacritty tmux neovim nitrogen nordic-wallpaper z ripgrep stow i3blocks yad suckless-tools python python-pip python-neovim zsh; do
	echo "Y" | sudo pacman -S $app;
	if [[ $? -eq 1 ]]; then
		yay $app;
	fi
done
rm -rf ~/.config/i3 .zshrc ~/.config/user-dirs.dirs ~/.Xresources
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
sudo chsh -s /bin/zsh
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
